cloud:
  aws:
    region:
      static: eu-north-1
      auto: false
    credentials:
      access-key: your-access-key
      secret-key: your-secrete-key
    end-point:
      uri: https://sqs.eu-north-1.amazonaws.com/985539766483/first-queue 
      

logging:
  level:
    org.springframework: INFO
    com.cybage: INFO
    com.amazonaws.monitoring: ERROR
    com.amazonaws: DEBUG
    
    